version: '3.8'

services:
  aws-manager-bot:
    build: .
    container_name: aws-manager-bot
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - GRUPO_AUTORIZADO_ID=${GRUPO_AUTORIZADO_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"